Sunbeam
IntegrierBar/FPComputerGames pull request #44
Opened 2024-09-12 16:45 UTC by zebleck

updates the sunbeam to actually raycast its beam along the direction the player is looking, being blocked by tiles.

also:

- introduces lighting system to make the spells pop more
- adds particles to normal spells as well as impact explosions with light and particles

2024-09-13 10:18 UTC, IntegrierBar requested changes
Paar Kleinigkeiten, aber vorallem funktioniert das Wechseln der Räume nicht mehr.
Ich glaube das liegt daran, dass du die collision_layer vom player geändert hast.

2024-09-13 10:18 UTC, IntegrierBar commented on TheMagicApprentice/modules/entities/player/spells/sun_beam/SunBeam.cs
> +		polygonPoints = ConvexHull(polygonPoints);
Warum Konvexe Hülle? 
Wenn die Hälfte des Strahls blockiert wird durch die Wand, und die andere Hälfte weiter geht, dann sollte das doch nicht konvex sein?

2024-09-13 10:18 UTC, IntegrierBar commented on TheMagicApprentice/modules/entities/player/spells/sun_beam/SunBeam.cs
> +	private float Cross(Vector2 o, Vector2 a, Vector2 b)
Die Funktion sollte static sein.
Die Funktion gibt es btw bereits in Godot: (a-o).Cross(b-o)

2024-09-13 10:18 UTC, IntegrierBar commented on TheMagicApprentice/modules/entities/slimes/slime.tscn
> +collision_layer = 2
Auch hier, warum änderst du die collision_layer und collision_mask der Slimes?

2024-09-13 10:18 UTC, IntegrierBar commented on TheMagicApprentice/project.godot
Wofür sind die neuen render und physics layer "Beam"?
Soweit ich sehen kann, werden die nirgends verwendet.

2024-09-21 20:42 UTC, zebleck commented on TheMagicApprentice/project.godot
DIe neuen Occlusion Layers sind für das Lighting system (wobei das Licht des Spielers und das Licht des Beams teilweise verschiedene Kollisionen haben, deswegen zwei Layers).

zb hier:
![image](https://github.com/user-attachments/assets/f5dd4947-560a-4ab1-9acf-3b72eb348a30)

2024-09-21 20:50 UTC, zebleck commented
dnake fürs rüberschauen, habe die layers wieder auf 1 gesetzt und die convex hull rausgenommen. hatte das mit den layern anfangs gemacht, da beam bisschen andere kollisionen wie der spieler hat aber jetzt scheint es auch mit layer 1 zu funktionieren.

2024-09-23 20:11 UTC, IntegrierBar approved these changes
Sieht gut aus

2024-09-23 20:21 UTC, merged